version: '3'

services:
  shipservice1:
    build: ./ship-service
    networks:
      - internet
      - internal
    ports:
      - "8081:8081"

  emergencyservice1:
    build: ./emergency-service
    networks:
      - internet
      - internal
    ports:
      - "8082:8082"

  scheduleservice1:
    build: ./schedule-service
    networks:
      - internet
      - internal
    ports:
      - "8083:8083"
  scheduleservice1:
    build: ./headquarter-ui
    networks:
      - internet
      - internal
    ports:
      - "8084:8084"
networks:
  internet:
    name: internet
  internal:
    driver: bridge
    name: internal