apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ship
  name: ship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ship
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ship
    spec:
      containers:
      - image: ship
        imagePullPolicy: "Never"
        name: ship
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
