apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: emergency
  name: emergency
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    app: emergency
status:
  loadBalancer: {}
