apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: headquarter
  name: headquarter
spec:
  ports:
  - name: "8084"
    port: 8084
    targetPort: 8084
  selector:
    app: headquarter
status:
  loadBalancer: {}
