apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: schedule
  name: schedule
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    app: schedule
status:
  loadBalancer: {}
