apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: schedule
  name: schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: schedule
    spec:
      containers:
      - image: schedule
        imagePullPolicy: "Never"
        name: schedule
        ports:
        - containerPort: 8083
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
