---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftl-site
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: emergency-service
          image: nginx
          ports:
            - containerPort: 8081
        - name: rss-reader
          image: nickchase/rss-php-nginx:v1
          ports:
            - containerPort: 88