apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
  namespace: soa
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - image: activemq
          name: activemq
          imagePullPolicy: Never
          resources:
            requests:
              memory: 600Mi
              cpu: 200m
            limits:
              memory: 1000Mi
              cpu: 400m
      restartPolicy: Always