apiVersion: apps/v1
kind: Deployment
metadata:
  name: headquarter-ui
  namespace: soa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headquarter-ui
  template:
    metadata:
      labels:
        app: headquarter-ui
    spec:
      containers:
      - name: headquarter-ui
        image: headquarter-ui
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

  